version: "3.8"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
            - MONGO_INITDB_DATABASE=investment-portfolio
            - MONGO_INITDB_ROOT_USERNAME=username
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - /d/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - /d/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped